spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/netDisk?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Shanghai
    username: root
    password: root
  mvc:
    view:
      prefix: /pages/
      suffix: .jsp
  servlet:
    multipart:
      max-file-size: 10MB
  redis:
    host: localhost
    port: 6379
  mail:
    host: smtp.163.com
    username: registTZ@163.com
    password: BEVFUCPTGZJJQFTK
    default-encoding: UTF-8

server:
  port: 8888
  tomcat:
    uri-encoding: UTF-8

NetDisk:
  fileStorePath: 'F:/Cui/fileStore'
  userIconFolder: 'UserIcon'
  pageSize: 5