spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/netDisk?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Shanghai
    username: root
    password: root
  mvc:
    view:
      prefix: /pages/
      suffix: .jsp
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB
  redis:
    host: localhost
    port: 6379
  mail:
    default-encoding: UTF-8
    host: smtp.163.com
  profiles:
    active: prop

server:
  port: 8888
  tomcat:
    uri-encoding: UTF-8

NetDisk:
  fileStorePath: 'F:/Cui/fileStore'
  userIconFolder: 'UserIcon'
  pageSize: 5
  shareFolder: 'share'

logging:
  level:
    com.catchiz.mapper: debug